### ISSUE TITLE
sddm: add support

### ISSUE THREAD

**Issue by LucaGawa** [danth/stylix#409] opened 2024-06-02 10:00 UTC
I saw that lightdm is already supported, but for me it would be really great, if there where a support for sddm too!

**Comment by LucaGawa** [comment] 2024-06-02 10:07
I just found out, that it is a duplicate of:  https://github.com/danth/stylix/issues/74#issue-1644708226

**Comment by danth** [comment] 2024-06-02 11:44
Duplicate of #74

**Closed by danth** 2024-06-02 11:44 UTC
Labels: duplicate, feature
