### ISSUE TITLE
The option `home-manager.users.redacted.wayland.windowManager.hyprland.settings' does not exist.

### ISSUE THREAD

**Issue by HenkVanMaanen** [danth/stylix#193] opened 2023-11-27 17:04 UTC
I get this error when importing the stylix nixos module on nixos 23.11. Is it a configuration error or is this a stylix / homemanager error?

`The option `home-manager.users.redacted.wayland.windowManager.hyprland.settings' does not exist.`

**Comment by danth** [comment] 2023-11-29 20:39
This option was added to Home Manager quite recently, so you might need to update your Home Manager version.

If you're using Hyprland: make sure you aren't importing the Hyprland module from the Hyprland flake, as this will override the module which is built in to Home Manager. Migrating to the built in module should be simple because it's backwards compatible.

Duplicate of #152

**Closed by danth** 2023-11-29 20:39 UTC
