### ISSUE TITLE
Broken build on stylix/release-24.05

### ISSUE THREAD

**Issue by zmitchell** [danth/stylix#645] opened 2024-11-25 23:40 UTC
Hi, initially I thought my problem was the same one as in #642, but I think it's a different problem.

Here is the error trying to build my flake:
```
error:
       … while evaluating the attribute 'value'
         at /nix/store/ly4s3hw35dd1c2vsd694y2715pc1d2c1-source/lib/modules.nix:809:9:
          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build':

       … while evaluating the attribute 'mergedValue'
         at /nix/store/ly4s3hw35dd1c2vsd694y2715pc1d2c1-source/lib/modules.nix:844:5:
          843|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          844|     mergedValue =
             |     ^
          845|       if isDefined then

       … while evaluating definitions from `/nix/store/did8vrf5l7f35f3c5sx6s6mwjfczcym7-source/modules/system':

       … while evaluating the option `home-manager.users.zmitchell.home.file':

       … while evaluating definitions from `/nix/store/q1ss75nhmjiydyqw8lbzwbx7cqk8z0qq-source/modules/xresources.nix':

       … while evaluating the option `home-manager.users.zmitchell.xresources.properties':

       … while evaluating definitions from `/nix/store/879kb7aars4jciwdxxkfiins9kbym5rg-modules/xresources/hm.nix':

       … while evaluating the option `home-manager.users.zmitchell.stylix.base16Scheme':

       … while evaluating definitions from `/nix/store/q1ss75nhmjiydyqw8lbzwbx7cqk8z0qq-source/nixos/common.nix':

       … while evaluating the option `stylix.image':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: The option `stylix.image' is used but not defined.
```

I actually have that option commented out, so I'm not even using it in my flake. My `stylix` input is coming from the `release-24.05` branch. The lockfile from that branch shows that the `base16.nix` input is locked to a revision _before_ the `slugify` issue that was the root cause of #642, so I'm confused as to what's happening.

My flake is here: https://github.com/zmitchell/nixos-configs/blob/3eb99eb53d7f7cc8cb243071cf073f9da26ac553/flake.nix

And the relevant `stylix` config is here (note that the `stylix.image` line is still there, this is where I encountered the issue and I commented it out while troubleshooting, but the issue persists): https://github.com/zmitchell/nixos-configs/blob/3eb99eb53d7f7cc8cb243071cf073f9da26ac553/hosts/chonker.nix#L97

**Comment by zmitchell** [comment] 2024-11-26 00:45
Setting the input to the main branch got me unstuck.

**Comment by DanMyers300** [comment] 2024-12-06 01:46
Experiencing same issue. Attempted to set input to main branch and no luck.

```
error:
       … while calling the 'seq' builtin
         at /nix/store/45bzbkwnyb6nikgc7jkrn7vjibhy4xhk-source/lib/modules.nix:334:18:
          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          335|         _module = checked (config._module);

       … while evaluating a branch condition
         at /nix/store/45bzbkwnyb6nikgc7jkrn7vjibhy4xhk-source/lib/modules.nix:273:9:
          272|       checkUnmatched =
          273|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [] then
             |         ^
          274|           let

       … while evaluating the option `stylix.base16Scheme':

       … while evaluating the option `stylix.image':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: The option `stylix.image' was accessed but has no value defined. Try setting the option.
```

Stack trace:
```
       … while evaluating the option `stylix.image':

       … while evaluating the attribute 'mergedValue'
         at /nix/store/45bzbkwnyb6nikgc7jkrn7vjibhy4xhk-source/lib/modules.nix:851:5:
          850|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          851|     mergedValue =
             |     ^
          852|       if isDefined then

       … while calling the 'throw' builtin
         at /nix/store/45bzbkwnyb6nikgc7jkrn7vjibhy4xhk-source/lib/modules.nix:859:9:
          858|         # handling.  If changed here, please change it there too.)
          859|         throw "The option `${showOption loc}' was accessed but has no value defined. Try setting the option.";
             |         ^
          860|

       error: The option `stylix.image' was accessed but has no value defined. Try setting the option.
```

Stylix.nix:
```
  stylix = {
    enable = true;
    autoEnable = false;
    base16Scheme = "${pkgs.base16-schemes}/share/themes/outrun-dark.yaml";
    #image = pkgs.fetchurl {
    #  url = "https://images.unsplash.com/photo-1511800453077-8c0afa94175f";
    #  sha256 = "sha256-jGi50sy6Zjc1xuop670lFBA2UX3mvekB+EA4Fenjeek";
    #};
    polarity = "dark";
    cursor = {
      package = pkgs.adwaita-icon-theme;
      size = 7;
      name = "Adwaita";
    };
    #targets = {
    #  neovim = {
    #    enable = true;
    #    transparentBackground.main = true;
    #  };
    #};
  };
```

**Comment by trueNAHO** [comment] 2024-12-06 13:43
Is this issue a duplicate of https://github.com/danth/stylix/issues/421?

**Closed** 2024-12-06 13:45 UTC
