### ISSUE TITLE
doesn't work with latest tinted-theming

### ISSUE THREAD

**Issue by nazarewk** [danth/stylix#571] opened 2024-09-24 12:49 UTC
Not sure what is going on here, but seems to be some changed standards and missing coordination between projects?
- https://github.com/tinted-theming/tinted-foot/issues/8#issuecomment-2371141311

**Comment by trueNAHO** [comment] 2024-09-24 13:34
> Not sure what is going on here

What exactly is the problem?

It seems that https://github.com/tinted-theming renamed some of their repositories. I will submit a Stylix PR for this.

**Comment by nazarewk** [comment] 2024-09-24 13:42
they also:
- changed data structure, see the [`config.yaml`](https://github.com/tinted-theming/tinted-foot/commit/7ca954e993ee73a7cc9b86c59df4920cc8ff9d34#diff-46d429f4b19179f06d6ff725d2dc2c8d24914503d59c4ab5fb27a0330b2c445f)
- YAML parser started failing on `[aString]` list

**Comment by trueNAHO** [comment] 2024-09-24 14:29
@nazarewk, I have not looked into this yet. Could you clarify what exactly is the problem with the current `tinted-foot` verision?

**Comment by danth** [comment] 2024-09-24 22:54
#572 has been merged; has this improved the situation?

**Comment by nazarewk** [comment] 2024-09-25 07:07
#572 didn't change anything, but updating `tinted-foot` will result in:
```
trace: Warning (base16.nix): failed to parse YAML file without an IFD.
trace: Warning (base16.nix): A config.yaml does not follow base16 conventions or was incorrectly parsed.
Defaulting to an empty extension.
Please consult https://github.com/SenchoPens/base16.nix/tree/main#%EF%B8%8F-troubleshooting
trace: Warning (base16.nix): failed to parse YAML file without an IFD.
trace: Warning (base16.nix): A config.yaml does not follow base16 conventions or was incorrectly parsed.
Defaulting to an empty extension.
Please consult https://github.com/SenchoPens/base16.nix/tree/main#%EF%B8%8F-troubleshooting
base16-nix-parse-check> Running phase: checkPhase
base16-nix-parse-check> Output of "jd /nix/store/w0j2i02sfmpl19jmnprrd5ll4l068yj0-fromYAML /nix/store/nzxhrh19vbjzsnz1wb896w45y0wfdjnm-parsed-yaml-as-json":
base16-nix-parse-check> @ ["base16","supported-systems"]
base16-nix-parse-check> - ["base16"]
base16-nix-parse-check> + "[base16]"
base16-nix-parse-check> @ ["base24","supported-systems"]
base16-nix-parse-check> - ["base24"]
base16-nix-parse-check> + "[base24]"
base16-nix-parse-check> Error (base16.nix): /nix/store/rqh827dzqi5n11vwfv21gggwaaf24338-source/templates/config.yaml was parsed incorrectly during nix evaluation.
base16-nix-parse-check> Please consult https://github.com/SenchoPens/base16.nix/tree/main#%EF%B8%8F-troubleshooting
home-manager-path> created 4071 symlinks in user environment
```

**Comment by trueNAHO** [comment] 2024-10-09 18:41
> updated stylix today and having the same issue with nord now with kitty and tmux

Is this caused by https://github.com/danth/stylix/pull/588?

**Comment by aacebedo** [comment] 2024-10-09 18:57
> > updated stylix today and having the same issue with nord now with kitty and tmux
> 
> Is this caused by #588?

it seems. I reverted stylix to 63426a59e714c4389c5a8e559dee05a0087a3043 and I can complie

**Comment by trueNAHO** [comment] 2024-10-09 18:58
I am already looking into this. I will try to properly resolve this today.

**Comment by trueNAHO** [comment] 2024-10-09 21:16
> I am already looking into this. I will try to properly resolve this today.

Feel free to test https://github.com/danth/stylix/pull/589 and leave a comment if it works.

**Comment by noahfraiture** [comment] 2024-10-11 10:10
Hello,
I have the same issue even on https://github.com/danth/stylix/commit/63426a59e714c4389c5a8e559dee05a0087a3043
However this is my first time using nixos, I might have done something wrong. This is how I declare it in flake.nix `stylix.url = "github:danth/stylix?rev=63426a59e714c4389c5a8e559dee05a0087a3043";` 
And I try to use it simply by setting enable to true and give it an image

**Comment by aacebedo** [comment] 2024-10-11 10:21
> > I am already looking into this. I will try to properly resolve this today.
> 
> Feel free to test #589 and leave a comment on whether it works.

I confirm it works

**Closed** 2024-11-08 18:26 UTC
