### ISSUE TITLE
[Feature] Get the closest color name

### ISSUE THREAD

**Issue by anotherhadi** [danth/stylix#587] opened 2024-10-06 15:19 UTC
For some apps, colors can only be sets with colors name (blue, cyan, black, white, ...)
It would be cool to access the closest color name through config.lib.colors.name.baseXX or something like that.

**Comment by danth** [comment] 2024-10-06 19:11
I believe this is already implemented upstream:

https://github.com/SenchoPens/base16.nix/blob/c89c8123310257f3ddc04cc59aa4b5573c6d515f/lib/colors.nix#L92-L107

**Comment by anotherhadi** [comment] 2024-10-06 21:34
If I'm not mistaken, this is the inverse of what I need!
The goal is to give a name for a specific base, and not a base for a specific name

**Comment by trueNAHO** [comment] 2024-10-06 22:02
> The goal is to give a name for a specific base, and not a base for a specific name

In the future, https://github.com/danth/stylix/issues/249#issuecomment-2012933635 would resolve this.

**Comment by trueNAHO** [comment] 2024-10-07 14:44
@anotherhadi, should we close this issue as a duplicate of https://github.com/danth/stylix/issues/249?

**Comment by anotherhadi** [comment] 2024-10-07 15:13
> @anotherhadi, should we close this issue as a duplicate of https://github.com/danth/stylix/issues/249?

That's not mentioned but could be added in the comments of #249

**Comment by trueNAHO** [comment] 2024-10-07 17:35
> That's not mentioned but could be added in the comments of #249

For example, the Vim highlight groups would instantiate the following named colors:

> ```
> 							*hl-ColorColumn*
> ColorColumn	Used for the columns set with 'colorcolumn'.
> 							*hl-Conceal*
> Conceal		Placeholder characters substituted for concealed
> 		text (see 'conceallevel').
> 							*hl-CurSearch*
> CurSearch	Used for highlighting a search pattern under the cursor
> 		(see 'hlsearch').
> ```
>
> -- `nvim --cmd 'help highlight-groups'`

**Closed** 2024-10-07 17:36 UTC
